### ISSUE TITLE
Please obfuscate Steam64 IDs from users with DNT both on the /list command and in logs.

### ISSUE THREAD

**Issue by uncarve** [KarlOfDuty/SCPDiscord#104]
**Describe the bug**
The plugin's /list command and logs violate the VSR by ignoring the DNT flag on users that may have it enabled.

**To Reproduce**
1. Enable DNT
2. Join the server and connect the bot
3. Use /list, or do anything that logs an action

**Screenshots**
N/A

**Setup (please complete the following information):**
N/A

Please obfuscate Steam64 IDs from users with DNT both on the /list command and in logs.

**Comment by KarlOfDuty** [comment]
I will not be adding anything to remove players with DNT turned on from the logs. As we discussed, this would ruin a lot of the moderation aspects of this plugin.

Also per our previous discussion you claimed the existing steam id filter in the config didn't work, but this is incorrect as you can see here with the filter off/on:

![image](https://github.com/KarlOfDuty/SCPDiscord/assets/18099825/6770afb1-e637-4734-8dc5-77fa64fef225)

![image](https://github.com/KarlOfDuty/SCPDiscord/assets/18099825/a98c9210-1911-4a8e-aa78-e3791183faf3)

As the section we discussed implementing in discord already exists in the bot I will close this, you can reopen it if the solution doesn't work for your use case or something.
