### ISSUE TITLE
Disable Slash Commands

### ISSUE THREAD

**Issue by Oyplap** [KarlOfDuty/SCPDiscord#117]
**Describe what you want to be implemented**
Disables slash commands for the Discord bot. Less headache for administrators that see all slash commands and don't use them.

**Motivate why this change is needed/appreciated by the community**
It's a nice option to have for servers that never use the bot's slash commands. We currently host 4 active ones and see 4 times the kick command.

**Comment by emshov74** [comment]
![image](https://github.com/KarlOfDuty/SCPDiscord/assets/36211362/18e328ce-2ecd-490a-baa5-d719a6fd2b4a)
The voices are getting louder

**Comment by KarlOfDuty** [comment]
The voices are about to be silenced.
