### ISSUE TITLE
Add report embeds

### ISSUE THREAD

**Issue by panSecret** [KarlOfDuty/SCPDiscord#134]
**Describe what you want to be implemented**
When a player report is sent, the bot pings a specified role and sends an embed which includes: The name, Steam ID, and role of the reporter and the one who was reported, which server the report was sent from, and the reason provided.

**Motivate why this change is needed/appreciated by the community**
The default webhook reports are messy and lack some features mentioned above.

I'm not good at explaining so sorry if it reads badly.

**Comment by KarlOfDuty** [comment]
This is already in the next update :+1:
