### ISSUE TITLE
Fix escape message formatting

### ISSUE THREAD

**Issue by LaFesta1749** [KarlOfDuty/SCPDiscord#139]
Hey @KarlOfDuty 
I just installed the bot and plugin and I was testing it on a test server... so, here's my questions regarding 2 discord messages:

![image](https://github.com/KarlOfDuty/SCPDiscord/assets/1494298/6eac8e38-76dc-4ef3-8a9c-203fb92edcfe)

**First:** "died in an unknown way" is it possible to change it to how the player died? Personally I died to a tesla to test this

**Second:** "has escaped and become a <var:newclass>" what's var:newclass? I escaped as a Scientist and became MTF, can we fix this one too?

Thank you and have a great day! <3

**Comment by KarlOfDuty** [comment]
I'll have to have a look at the second one but the first one is when the game doesn't provide a specific damage type.

**Comment by LaFesta1749** [comment]
But doesn't tesla deal damage?

Same thing happened when I jumped off and died - still said "unknown way".

**Comment by KarlOfDuty** [comment]
Think it used a universal damage handler iirc.
