### ISSUE TITLE
english.yml config small oopsie

### ISSUE THREAD

**Issue by Oyplap** [KarlOfDuty/SCPDiscord#146]
"onpocketdimensionenter" is:

`<var:player-name> (<var:player-userid>) was taken into the SCP-106 pocket dimension by <var:attacker-name> (<var:attacker-userid>).`

But it should be:

`<var:target-name> (<var:target-userid>) was taken into the SCP-106 pocket dimension by <var:attacker-name> (<var:attacker-userid>).`

Literally unusable plugin

**Comment by KarlOfDuty** [comment]
i forgor :skull:
