### ISSUE TITLE
Filter certain commands into channel

### ISSUE THREAD

**Issue by BenFRC5147** [KarlOfDuty/SCPDiscord#148]
The ability to filter when a player runs a certain command would be pretty sick, and be helpful to keep just a command log while still having event logs elsewhere.

**Comment by KarlOfDuty** [comment]
Could you give some more information on what exactly you want the feature to do?

**Comment by BenFRC5147** [comment]
For instance, we have a plugin that adds an economy that players can use the tilde console to interact with commands such as .buy/.sell/.deposit etc, it would be nice if I could specify “buy”,”sell” etc to filter into another discord channel that I could designate as “Economy-command-logs” that is separate from the normal console commands so I can see those high importance commands without the flood of the other console commands

**Comment by KarlOfDuty** [comment]
Could you send commands to several channels and use the cancel regex to remove the ones you don't want?

If not, how exactly would this work when it comes to configuring it? A pattern to override the channel id? That could cause issues with things like discord command responses.
