### ISSUE TITLE
Bot status playercount change proposal

### ISSUE THREAD

**Issue by Oyplap** [KarlOfDuty/SCPDiscord#15]
**Describe what you want to be implemented**
Could you perhaps change the way how to the playercount on the bot's status look like? Or give us the option to change it in the config?

**Motivate why this change is needed/appreciated by the community**
How it looks right now feels and looks a little weird. Most of my bots look like the bots below (Server 1 & 2):
![Screenshot_2022-12-22_013820](https://user-images.githubusercontent.com/45702131/209160526-34313077-bf2a-425c-a070-1c312d44fed5.png)

**Comment by EsserGaming** [comment]
Honestly I kinda like the space between, but that's just preference.

**Comment by KarlOfDuty** [comment]
Yeah same, I will just add a config option for it.
