### ISSUE TITLE
Using steam64ID does not unban player

### ISSUE THREAD

**Issue by Vikkichu** [KarlOfDuty/SCPDiscord#154]
When command /unban (steamid) is used the following messages it posted, "All entries with SteamID/IP 'streamid' have been cleared from the ban lists.". However the UserIdBans.txt document is not updated and the player is not unbanned

When the player's IP is unbanned using /unban (userIp) the IpBans.txt is updated and the player is unbanned HOWEVER the steam64ID still remains banned/not updated in the UserIdBans.txt document. 

Player is able to connect to server after IP unban but not ID unban

**Comment by KarlOfDuty** [comment]
Is this something you can recreate? I can't really get it to happen.

**Comment by KarlOfDuty** [comment]
This is only possible when players are banned using scpdiscord, not using the ingame commands. I have asked northwood to fix it on their end, we will see how that goes.
