### ISSUE TITLE
/unmute command posting wrong message on unmute

### ISSUE THREAD

**Issue by Vikkichu** [KarlOfDuty/SCPDiscord#155]
When unmuting via /unmute bot posts the following line 
""Player" (ID) was muted by Dedicated Server (server)."

Player is however unmuted

**Comment by KarlOfDuty** [comment]
I can't reproduce this behaviour, could you give me an example to check?

**Comment by KarlOfDuty** [comment]
![image](https://github.com/user-attachments/assets/5ac0bfb3-f9e8-4ce2-a254-4e4b5438eb18)
