### ISSUE TITLE
[SUGGESTION] Add support player-nickname for slash-commands

### ISSUE THREAD

**Issue by Bay62** [KarlOfDuty/SCPDiscord#161]
![image](https://github.com/KarlOfDuty/SCPDiscord/assets/56767731/aa1435ae-0897-490a-8c5e-5ef3031a3c60)
![image](https://github.com/KarlOfDuty/SCPDiscord/assets/56767731/89c0861b-4eea-4331-aa42-e589ce354c4e)

**Comment by KarlOfDuty** [comment]
I have added discord user metadata to all discord commands so it can now be used in the language configs.
