### ISSUE TITLE
Add /Playtime

### ISSUE THREAD

**Issue by lux-zero-161** [KarlOfDuty/SCPDiscord#163]
can you add that users could see their playing time with the command, then there was no need to look at /playerinfo anymore <3 <3

/Playtime steamid""
/Playtime user:""  <- Discord Synced

![Screenshot 2024-05-12 174136](https://github.com/KarlOfDuty/SCPDiscord/assets/128979226/28c02521-b725-4022-93f0-47038e7d8fba)

**Comment by KarlOfDuty** [comment]
Is there a reason to use separate commands for the playtime and the other player info?

**Comment by KarlOfDuty** [comment]
Also, I don't think I have access to a first join time, so that would have to be a new thing to start tracking.
