### ISSUE TITLE
[BUG] Useless info when player dies, or joins/leaves

### ISSUE THREAD

**Issue by BoozyAF** [KarlOfDuty/SCPDiscord#18]
**Describe the bug**
This is about the messages the bot sends in the discord channel:

When a player joines or leaves, they become a "None", which is pretty useless info since we know that a player has joined or left.
When a player dies, it says that they'd become a class/role they were before for a moment and then sets them to spectator.

**To Reproduce**
Just make sure you have player **JOIN**/**LEFT** and player set **ROLE**(dont exactly remember what it actually was)/**CLASS** enabled in the config. The messages should be seen in the discord channel that you have set for those messages.

**Screenshots**
​​​
![image](https://user-images.githubusercontent.com/35653838/209723263-b306c869-5d9b-46e8-8a7d-ee20fd1151d0.png)
‌​‌​​‌‌​‌​‌‌‌‌​​‌​‌​‌​​​‌​‌​​​​‌‌​​‌‌​‌​​​‌​​‌‌‌​​‌‌‌​‌​‌

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - SCP Server Version: 12.0.0

**Comment by KarlOfDuty** [comment]
Should be fixed now.
