### ISSUE TITLE
[BUG] Bot crash for text over 4096 characters

### ISSUE THREAD

**Issue by terminator-97** [KarlOfDuty/SCPDiscord#33]
**Describe the bug**
The bot crash if the message is too long (4096+ characters)

**To Reproduce**
1. Execute a command that will print over than 4096 characters
2. Bot crash

**Screenshots**
-

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 3.0.0 alpha 3
 - API Version: bot version

**Comment by KarlOfDuty** [comment]
Could you provide a screenshot?

**Comment by terminator-97** [comment]
![immagine](https://user-images.githubusercontent.com/50580453/210291886-b3f74aef-687d-439c-bec2-8d3808b3631a.png)

![immagine](https://user-images.githubusercontent.com/50580453/210291989-c9f29f85-3432-43ce-b1cf-c92c456762f0.png)
