### ISSUE TITLE
Log the "oban" command together with the onban messages.

### ISSUE THREAD

**Issue by Scorpio622** [KarlOfDuty/SCPDiscord#43]
**Describe what you want to be implemented**
Log the "oban" command together with the onban messages.

**Motivate why this change is needed/appreciated by the community**
messages:
    onban:
        player: [ "bans" ]
        server: [ "bans" ]

This event currently only logs bans made directly to online players, it would be nice to have the oban command also be logged in the same category. This would benefit everyone that has a dedicated bans channel.

**Comment by KarlOfDuty** [comment]
Requested the event in the API. https://github.com/northwood-studios/NwPluginAPI/issues/180
