### ISSUE TITLE
[BUG] grenage

### ISSUE THREAD

**Issue by klingelschmidt** [KarlOfDuty/SCPDiscord#65]
My chat says grenage when someone dies from a grenade idk why

1. Join KarlOfDuty.com Server 2
2. Spawn as MTF sergeant
3. Throw grenade in elevator
4. See below

![Skärmbild](https://user-images.githubusercontent.com/60178327/225121716-e14a157b-45fe-4890-8a26-33b64104f616.png)

**Setup (please complete the following information):**
 - OS: IDK whatever karlofduty runs on
 - Version: See above
 - API Version: what is this?

**Comment by KarlOfDuty** [comment]
This was fixed a few months ago, use the dev builds if you want the fix.
