### ISSUE TITLE
[BUG] +Server ban ISSUE 

### ISSUE THREAD

**Issue by DrBakerCat** [KarlOfDuty/SCPDiscord#68]
+server ban command fails to show the actual reason of the ban.  Even when a comment is written of the why it leaves it blank

**Comment by KarlOfDuty** [comment]
The server ban command doesn't have a reason parameter
![image](https://user-images.githubusercontent.com/18099825/226117061-0f0d0e3b-93cc-45f8-b3f0-6824b30b0607.png)
