### ISSUE TITLE
When command has wrong arguments show usage of this command

### ISSUE THREAD

**Issue by VALERA771** [KarlOfDuty/SCPDiscord#74]
**Describe what you want to be implemented**
When you using bot commands like ban/unban and etc will be good if "Invalid arguments" will be replaced with command example/required arguments 

**Motivate why this change is needed/appreciated by the community**
Blame me if I blind and can't find usage for this commands, but I need to see code and how they're implemented, to see which arguments I need to use

**Comment by KarlOfDuty** [comment]
How exactly are you using the command? I can't really get it to use the command without showing the arguments.

**Comment by KarlOfDuty** [comment]
And if you want to list all the commands without reading the code you can use the /help command and click on the command documentation link.

**Comment by VALERA771** [comment]
> How exactly are you using the command? I can't really get it to use the command without showing the arguments.

Just using it with any arguments or not correct amount of them

> And if you want to list all the commands without reading the code you can use the /help command and click on the command documentation link.

Yes, but this will be also useful

**Comment by KarlOfDuty** [comment]
> Just using it with any arguments or not correct amount of them

Yeah but how, Discord will literally not allow me to send the message without the required arguments

**Comment by KarlOfDuty** [comment]
Like when I type it and press enter it shows this and refuses to send the command:
![image](https://user-images.githubusercontent.com/18099825/229625822-6282a965-64d9-4b12-bad5-a752a34e5125.png)

**Comment by VALERA771** [comment]
On server we doesn't have slash commands. They're already implemented?

**Comment by KarlOfDuty** [comment]
Yep in 3.1.0
