### ISSUE TITLE
[BUG] Bot unable to start with dotnet 7

### ISSUE THREAD

**Issue by mrnoahfink** [KarlOfDuty/SCPDiscord#75]
**Describe the bug**

**To Reproduce**
1. Go to 'Open Folder where you kept SCPDiscord
2.  Open the terminal then do ./SCPDiscordBot
3. Hopefully starts, but nah. I set the permission folder to 777 and install dotnet 7, then did the same thing with the same error. 

**Screenshots**

![IMG_5799](https://user-images.githubusercontent.com/66857858/229308140-4e489ffb-2fd2-47cd-bca8-0a9f4df92f54.jpg)

**Setup (please complete the following information):**
 - OS: Ubuntu 20.0.4.2 LTS
 - Version: [Latest Dev Master]

**Comment by KarlOfDuty** [comment]
You are trying to run a directory, you have to run the actual application.

**Comment by mrnoahfink** [comment]
I got to work but seems bot not turning online, I will keep looking into this.

**Comment by mrnoahfink** [comment]
Stuck at this.

![unnamed](https://user-images.githubusercontent.com/66857858/229334875-56e1cba9-b3aa-43d2-8227-ec324e54a3a7.jpg)

**Comment by KarlOfDuty** [comment]
I have never seen this happen before, have you made any code changes? Have you tried it using the release version?

**Comment by mrnoahfink** [comment]
The code itself like config,yml, etc from Master branch. The SCPDiscordBot is from release version.

**Comment by KarlOfDuty** [comment]
Well the config should be the same in the release version and the master branch but why did you get the config from there? The bot creates it if it doesn't exist as it says in the guide.

Do you have a firewall blocking outgoing connections maybe? I really don't know what could be wrong here, at this point it hasn't really done anything yet that even can go wrong.

**Comment by KarlOfDuty** [comment]
Also try turning debug mode on in the config. And send your config here without the token in it.

**Comment by KarlOfDuty** [comment]
I downloaded the latest release and ran it now and only set the bot token and it seems to work fine:
![image](https://user-images.githubusercontent.com/18099825/229369630-8ee9dcce-4eae-4054-9dff-985f40e2cab0.png)
