### ISSUE TITLE
[BUG] Any player with access to RA can set any group he want

### ISSUE THREAD

**Issue by VALERA771** [KarlOfDuty/SCPDiscord#76]
**Describe the bug**
Using command scpd_gvr any user with access to RA can set any group any won't. No permission check there

**To Reproduce**
1. Open RA
2. Type `pm setgroup <id> <any group which have only access to RA>`
3. Type `scpd_gvr owner`
4. You now has an owner group!

**Screenshots**
No screenshoots, very easy to reproduce

**Setup (please complete the following information):**
 - OS: i think don't matter
 - Version: latest
 - API Version: latest

**Comment by KarlOfDuty** [comment]
Yeah I guess they shouldn't be RA commands as this API doesn't have any kind of permission checks.

**Comment by KarlOfDuty** [comment]
You can get the latest dev build if you want the fix.
