### ISSUE TITLE
[BUG] Steamids filter doesnt work 100% of the time on certain events

### ISSUE THREAD

**Issue by Scorpio622** [KarlOfDuty/SCPDiscord#77]
**Describe the bug**
Steamids filter doesnt work 100% of the time on certain events. Tried it out on a new channel for 15 minutes with 5 people on the server, seems to work most of the time (And for most events Id believe), but occasionally events like onplayerleave-onroundrestart-onplayerdie will send steamids, regardless if the channel is supposed to filter steam ids.

Its not all of the time, sometimes the filter works correctly in those events, but occasionally it will just send the steamid instead of the playerid. My guess is that it has something to do when the player becomes "null", for some reason.

**To Reproduce**
1. Go to plugin config
2. Add a Discord channel
3. Add the channel name to channelsettings: filtersteamids [ "name" ]
4. See the Discord channel messages

**Comment by KarlOfDuty** [comment]
Yes, if the player is not online anymore their steamid cannot be removed as the server doesn't have it.

**Comment by KarlOfDuty** [comment]
Added a note about this to the config.
