### ISSUE TITLE
[BUG] Server freezes upon round restart when plugin syncs roles from discord to in-game players.

### ISSUE THREAD

**Issue by CBADavid** [KarlOfDuty/SCPDiscord#87]
**Describe the bug**
Upon round restart, when people with synced roles are joining and their roles are being given to them, server waiting timer freezes. Round restart is not possible, only fix is to power off and power on the server.

**Screenshots**
![image](https://github.com/KarlOfDuty/SCPDiscord/assets/136242050/1772e384-a77b-401c-853c-5964a30cbd47)

**Setup:**
 - OS: Ubuntu 20.04
 - Pterodactyl panel Docker Container
 - 4 threads CPU
 - 6GB RAM
 - 8GB storage (1GB used)

**Comment by KarlOfDuty** [comment]
Hello, are you still having this issue? Does it still happen if you don't use the broadcast command in rolesync?
