### ISSUE TITLE
Add a right to execute all commands

### ISSUE THREAD

**Issue by VALERA771** [KarlOfDuty/SCPDiscord#92]
**Describe what you want to be implemented**
Rights in bot config (like in EXILED/NWAPIPS .*) which allows you to execute all available commands

**Motivate why this change is needed/appreciated by the community**
Too long and hard to write all commands (rnr, pm, etc). Easier is add a permissions which will allow you to execute any command

**Comment by KarlOfDuty** [comment]
This is already available. The permissions use regex matching.
