### ISSUE TITLE
[BUG] plugin crashes right after it gets enabled

### ISSUE THREAD

**Issue by jirka086** [KarlOfDuty/SCPDiscord#96]
**Describe the bug**
when starting server SCPDiscord loads everything sucesfully says [SCPDiscord] SCPDiscord 3.1.3 enabled. but few miliseconds after: [Error] [PluginAPI] Failed loading plugin SCPDiscord

**To Reproduce**
1. fresh install plugin and bot
2. set up configs for bot and plugin
3. start or restart the server

**Screenshots**
screenshot of error
![poplů](https://github.com/KarlOfDuty/SCPDiscord/assets/53871380/a655772c-8ed8-4ad5-a17a-c2ae477777b1)

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04, pterodactyl
 - Version: SCPDiscord 3.1.3
 - API Version: 12

**Comment by KarlOfDuty** [comment]
Could you send your config file and the full startup log? Also, I don't think it should make a difference but you could try using this build of SCPDiscord which I just built against the latest version of the API: https://jenkins.karlofduty.com/blue/organizations/jenkins/NWAPI%2FSCPDiscord/detail/master/146/artifacts

**Comment by jirka086** [comment]
the build you sent gives me the same issue here is my config file https://pastebin.com/4mqzjcbb

**Comment by KarlOfDuty** [comment]
Ok, I tried running it with your config on my end now and it works fine. Have you tried running it outside of the docker container?

Also, do you use different distros in the container and on the host machine?

**Comment by jirka086** [comment]
its setup how pterodactyl panel has it by default
its running official exiled egg 
and the plugin is in the official NW plugin api so exiled should not affectt it.

**Comment by jirka086** [comment]
fixed i put it in exiled plugin folder and it works
idk why it dosent work in official NW plugin api tho

**Comment by KarlOfDuty** [comment]
That is a bit bizzare, yes.
